SELECT
    CM.FORNECEDOR "Fornecedor",
    CM.NUMERONOTA "Numero da nota",
    ICM.CODPRODUTO "Código do produto",
    ICM.PRODUTO "Descrição do produto",
    COALESCE(ICM.VALORUNITARIOCOMPRA,0) "Valor unitário",
    ICM.QTDECOMPRA "Quantia comprada"

FROM
    TITEMCOMPRA ICM

LEFT JOIN
    TCOMPRA CM

ON
    ICM.CODCOMPRA = CM.CONTROLE

WHERE   
    CAST(CM.DATAHORACADASTRO AS DATE) BETWEEN '01/01/2024' AND '01/01/2025'
    AND CM.CODFORNECEDOR = '3' -- ALTERAR O FORNECEDOR AQUI, PELO CÓDIGO DELE

Order by
    CM.DATAHORACADASTRO